11.0 19.06c
ForgeFlow/ao-odoo-buildout pull request #15
Opened 2019-06-21 08:19 UTC by jbeficent

2019-06-21 12:27 UTC, MiquelRForgeFlow approved these changes

2019-06-26 12:55 UTC, MiquelRForgeFlow requested changes

2019-06-26 12:55 UTC, mreficent commented on buildout.cfg
> +    git https://github.com/Eficent/stock-logistics-warehouse.git parts/stock-logistics-warehouse11 11.0-add-stock_orderpoint_manual_procurement_location
delete this, they are repeated!

2019-06-26 13:56 UTC, jbeficent commented on buildout.cfg
> +    git https://github.com/Eficent/stock-logistics-warehouse.git parts/stock-logistics-warehouse11 11.0-add-stock_orderpoint_manual_procurement_location
Fixed

2019-07-02 22:15 UTC, merged